logging:
  level:
    root: info


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8890/alasDb
    username: alas
    password: alas
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql

url:
  ignore:
    swagger: /v2/api-docs, /webjars/*, /swagger-resources/, /actuator/health, /swagger-ui/index.html, /swagger-ui.html, /app//.{js,html}



springdoc:
  swagger-ui:
    path: /swagger